### ISSUE TITLE
Uninstall SpaceCalibrator

### ISSUE THREAD

**Issue by newgun066** [pushrax/OpenVR-SpaceCalibrator#10]
I seem to always have to reset calibration when using the Index. I don’t need this software anymore, and would like to now uninstall it so that I don’t have issues with the Index. How do I remove this software?

**Comment by pushrax** [comment]
You can uninstall with the regular add/remove programs feature of windows.

You can also fully reset the calibration by deleting the config file in Steam/config/01spacecalibrator

**Comment by pushrax** [comment]
Clicking "Clear Calibration" now deletes the config completely.
