### ISSUE TITLE
error when trying to download

### ISSUE THREAD

**Issue by sammithebull** [pushrax/OpenVR-SpaceCalibrator#116]
![20240208_135819](https://github.com/pushrax/OpenVR-SpaceCalibrator/assets/25556224/47403ab7-5d53-4839-a5b4-6b1a403ead81)

 i get this no matter what.  yes steam vr is already downloaded.  any suggestions or work arounds?

**Comment by Raivr-dev** [comment]
I see the word 'Fail...' twice in the screenshot in the other window. What does it say there?

**Comment by sammithebull** [comment]
![Uploading 20240208_181157.jpg…]()

**Comment by sammithebull** [comment]
![20240208_181157](https://github.com/pushrax/OpenVR-SpaceCalibrator/assets/25556224/5667fa9f-eef2-4bb7-90bf-11bad8e87dff)

**Comment by Raivr-dev** [comment]
Does SteamVR work fine, before you run this installer?
Did you try to run the installer as Administrator?

**Comment by sammithebull** [comment]
it finally installed but now it says hmd not found (108) whenever i try to open it

**Comment by Raivr-dev** [comment]
Do you know why it did install this time? What did you do differently? That could be of interest to other people that end up here in future.

**Comment by sammithebull** [comment]
im not sure. i just redownloaded it and it installed this time. but now im getting this whenever i try to start up the program.  any ideas on why this shows up
![20240209_163532](https://github.com/pushrax/OpenVR-SpaceCalibrator/assets/25556224/146ac2db-e9b0-4e7f-a97d-29da6766328d)

**Comment by Raivr-dev** [comment]
Can you start and run SteamVR without running SpaceCalibrator? Does your VR headset work fine in that case?

**Comment by sammithebull** [comment]
I figured it out.  Once my trackers were recognized by steamvr it ended up working.  Thanks for your help
