### ISSUE TITLE
Pimax with Rift CV1 Touch controllers

### ISSUE THREAD

**Issue by BrziJoe** [pushrax/OpenVR-SpaceCalibrator#12]
Hi, can somebody please add some steps for combination from headline. Also is it enough to have complete rift setup and only pimax hmd (without base stations)?
I tried to start oculus, then pimax, then spacecalibrator, but  can not get anything at same time in rift and pimax - one exclude other.

**Comment by pushrax** [comment]
Unfortunately the Rift CV1 controllers can't be used unless the Rift HMD is online - this is a limitation in the Oculus driver. When the Oculus driver is active in SteamVR it takes over completely.
