### ISSUE TITLE
Each trackers becomes a camera

### ISSUE THREAD

**Issue by Eddie821** [pushrax/OpenVR-SpaceCalibrator#14]
I use an oculus rift with 3 Vive trackers to play VRchat. When I turn the trackers on, each one becomes a camera in the VRchat application mirror, causing it to split into 4 sections, each showing a POV from their position and the last one is the headset position. They still work for full body, but I’m wondering how I can fix this because it kills my performance

**Comment by a1678991** [comment]
Delete externalcamera.cfg that exists in the VRChat installation directory.
Probably MR synthesis software such as LIV generated that file.
I don't think this issue is related to OpenVR-SpaceCalibrator.

**Comment by Eddie821** [comment]
> Delete externalcamera.cfg that exists in the VRChat installation directory.
> Probably MR synthesis software such as LIV generated that file.
> I don't think this issue is related to OpenVR-SpaceCalibrator.

you dont know how much you have helped me. thank you
