### ISSUE TITLE
vive cosmos?

### ISSUE THREAD

**Issue by untuned** [pushrax/OpenVR-SpaceCalibrator#19]
is support possible with the vive cosmos, until the new faceplate comes out?

**Comment by ithirzty** [comment]
Hi, I myself use openvr space calibrator with a vive cosmos and knuckles controllers and it works great! If you need more infos on how to do it you can contact me. Know that open vr space calibrator works natively with the vive cosmos.

**Comment by untuned** [comment]
> Hi, I myself use openvr space calibrator with a vive cosmos and knuckles controllers and it works great! If you need more infos on how to do it you can contact me. Know that open vr space calibrator works natively with the vive cosmos.

Add me on Discord, untuned#0001

**Comment by pushrax** [comment]
Thanks for confirming it works @ithirzty!
