### ISSUE TITLE
I cant install OpenVR-SpaceCalibrator

### ISSUE THREAD

**Issue by KingJason576** [pushrax/OpenVR-SpaceCalibrator#21]
when i install the program i get this error
![Annotation 2020-07-17 212253](https://user-images.githubusercontent.com/68484645/87863321-cf211b80-c90e-11ea-90ef-337ea8375e45.png)
im not sure what to do is there any way i can fix this?

**Comment by bluewolves01** [comment]
I'm having the same problem as well ;w; I don't know what to do!

**Comment by Eros1996** [comment]
I'm having the same problem as well.

**Comment by pushrax** [comment]
It appears that the OpenVR client library is unable to find the location where OpenVR is installed.

Can anyone who's running into this issue confirm the exact steps you took before running the installer? This may have something to do with running the installer from a temporary directory (e.g. from inside a zip file or somewhere the browser put it by default). It may also have something to do with permissions.

**Comment by monstermac77** [comment]
I just ran into this issue on a fresh Windows install. I tried running as admin to see if it was a permissions issue, same problem. The installer was located in my Downloads folder (that's where Chrome put it). Putting some keywords here to help people find this issue in the future: "Error opening file for writing:", "Failed to initialize OpenVR Installation path could not be located".

A reboot solved the issue for me. Since these issues didn't seem to persist for others (at least not enough for them to follow-up), I'm going to suggest this issue be closed.

**Comment by ibdnzgr** [comment]
I am having the same problem and rebooting my computer isn’t helping.

**Comment by monstermac77** [comment]
@ibdnzgr can you try a couple of the following? @PumpkinSpice said they heard some of these might help: 
* Running steam as admin
* Close SteamVR and try again (it shouldn't be running during install)
* Restarting computer

**Comment by ibdnzgr** [comment]
I downloaded the install executable. Do I need the zip file too? Ran the install from where it downloaded (downloads folder) and installed as administrator. 

![8B8F1E49-4531-459A-A387-B0EA8EB472AD](https://user-images.githubusercontent.com/77220268/104139523-ac2d6c80-5371-11eb-9249-26caabf62773.jpeg)

**Comment by monstermac77** [comment]
Should only need the executable. Unfortunately, I'm not sure what else to try. I would just quit the installation process, and try to start/stop SteamVR a couple times, run Steam as admin and then start VR, then stop VR, then try installing again and if that doesn't work restart your computer and then try installing again.

**Comment by pushrax** [comment]
@ibdnzgr do you still have this issue?

It seems odd that the Steam installation would be in %HOME%\AppData\Local\. Usually it's in Program Files.

**Comment by ibdnzgr** [comment]
Hi Pushrax... I guess the installer chose to put it there. I just clicked the executable that was downloaded. ????

**Comment by pushrax** [comment]
It would be interesting to see the log, and what it says for the "VR runtime path: " line.

The installer tries to detect where to install the driver by using VR_GetRuntimePath, part of the OpenVR API. Are there other SteamVR files already present in that path?

I should probably change it to use `vrpathreg adddriver` instead.

**Comment by ibdnzgr** [comment]
I am running the installer as admin with same results. Tell me what file to look for and I'll post the log. I got the hardware for my daughter and she is really looking forward to being able to use it with her Rift S. This seems to be the only software solution if we can get it working. Thanks for helping!

**Comment by pushrax** [comment]
The install log is in the installer window behind the error (if you drag the error box away you can see/copy the log).

It's possible to manually install. I will add instructions for how to do so to the README.

**Comment by ibdnzgr** [comment]
![IMG_2862](https://user-images.githubusercontent.com/77220268/108940875-ba7dd200-7619-11eb-87a2-a03f9b43abd7.jpg)
![IMG_2861](https://user-images.githubusercontent.com/77220268/108940922-cd90a200-7619-11eb-9dfb-11ff4254ee3c.jpg)

**Comment by pushrax** [comment]
Ah interesting. So VR_Init is failing, which is a core function as part of the SteamVR runtime. Do VR games run via SteamVR work?

**Comment by ibdnzgr** [comment]
Like Beat Saber?

**Comment by pushrax** [comment]
Any game that you launch through SteamVR rather than through the Oculus system.

**Comment by ibdnzgr** [comment]
@pushrax  yes  VR games work just fine through SteamVR.

**Comment by ibdnzgr** [comment]
@pushrax Could you please post manual install  instructions? I really want to make this work!!!! Thanks!

**Comment by pushrax** [comment]
Can you answer this question I posted above? Finding this is part of manual installation anyway:

Can you look for where your SteamVR installation actually is? Is it C:\Program Files (x86)\Steam\steamapps\common\SteamVR or something else? right click SteamVR in Steam Library -> Manage -> Browse Local Files

**Comment by ibdnzgr** [comment]
Yes the files are in that location.
Ian

On Friday, March 5, 2021, 12:57 PM, Justin Li <notifications@github.com> wrote:




Can you answer this question I posted above? Finding this is part of manual installation anyway:

Can you look for where your SteamVR installation actually is? Is it C:\Program Files (x86)\Steam\steamapps\common\SteamVR or something else? right click SteamVR in Steam Library -> Manage -> Browse Local Files

**Comment by ibdnzgr** [comment]
> 
> 
> Hey having the same issue wondering if there was ever a fix?

@pushrax you were saying maybe you could direct us how to manually install? Some way we can make this work? Thanks!

**Comment by Kricket-sys** [comment]
I've been having the same issues, Will a solution come soon for it?

**Comment by PumkinSpice** [comment]
Hey everyone — so I was successfully able to get someone through this error the other day. If you have more than one user on the system and aren’t the first user, try logging in as one of the other users and installing from there. This is an issue with some other vr-related programs as well. Unfortunately I don’t know what the fix might be, installer-wise.

**Comment by KingJason576** [comment]
it looks like user PumkinSpice has found a fix they said "Hey everyone — so I was successfully able to get someone through this error the other day. If you have more than one user on the system and aren’t the first user, try logging in as one of the other users and installing from there. This is an issue with some other vr-related programs as well. Unfortunately I don’t know what the fix might be, installer-wise". Anyways I was able to fix the issue by factory resetting my pc and that's the only thing that's worked for me I'm closing the issue today because its almost been a year since I've listed the issue and my Gmail is so full and I don't want to pay for more storage if Pumpkin's solution or mine doesn't work I'm sorry I cant help you but I hope you guys will get this issue fixed soon

**Comment by PumkinSpice** [comment]
Scroll all the way to the bottom and hit ‘unsubscribe’ — otherwise you’ll still get alerts if… say someone replies to you ;) (or if your bug is referenced elsewhere, etc).

> it looks like user PumkinSpice has found a fix they said "Hey everyone — so I was successfully able to get someone through this error the other day. If you have more than one user on the system and aren’t the first user, try logging in as one of the other users and installing from there. This is an issue with some other vr-related programs as well. Unfortunately I don’t know what the fix might be, installer-wise". Anyways I was able to fix the issue by factory resetting my pc and that's the only thing that's worked for me I'm closing the issue today because its almost been a year since I've listed the issue and I get emails every time someone comments something here and my Gmail is so full and I don't want to pay for more storage if Pumpkin's solution or mine doesn't work I'm sorry I cant help you but I hope you guys will get this issue fixed soon

**Comment by HyperRaccoon13** [comment]
> when i install the program i get this error ![Annotation 2020-07-17 212253](https://user-images.githubusercontent.com/68484645/87863321-cf211b80-c90e-11ea-90ef-337ea8375e45.png) im not sure what to do is there any way i can fix this?

My Fix was to ensure steam vr is fully installed, I tryed alot of stuff and the fix was just instaling steam vr
and it works now. so give that a try

**Comment by mint-cocoa** [comment]
beacuse  you dont have runtime. so dounload it on https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 on your cpu, maybe work it

**Comment by HyperRaccoon13** [comment]
Hm okay ill take note, i dont remeber if my issue was fixed after i made this, but thank you for the info, ill test some things out

kinda forgot i made this (commented on this)

**Comment by KannaMachi** [comment]
someone still facing this issue? just check on OpenXR on steam VR and set meta plugin compatibility to automatic or on. and install it. Your installation will not face any issues

**Comment by kenkenissocool** [comment]
Change install destination to the same directory as your Steam! Fixed for me!

**Comment by lorfanzo2005-cpu** [comment]
<img width="495" height="378" alt="Image" src="https://github.com/user-attachments/assets/c53ebb43-d4bd-422d-bdf5-fa34d720ec9f" />

**Comment by lorfanzo2005-cpu** [comment]
whenever i got to download space cal it says this

**Comment by lorfanzo2005-cpu** [comment]
<img width="1290" height="1125" alt="Image" src="https://github.com/user-attachments/assets/d3effbd2-7618-4468-9a84-19e644736ae1" />
