### ISSUE TITLE
Can win7 use this software?

### ISSUE THREAD

**Issue by azraeljian** [pushrax/OpenVR-SpaceCalibrator#22]
![2D358813-7039-40F0-9FB8-421903826E26](https://user-images.githubusercontent.com/16833943/89288786-c9566480-d688-11ea-9b99-c74933727345.jpeg)

**Comment by pushrax** [comment]
I think the garbled text is likely an encoding error with the system set to Chinese. It’s most likely working fine other than that message being wrong though, can you disable
