### ISSUE TITLE
Can I use this with SteamVR null driver?

### ISSUE THREAD

**Issue by tina1998612** [pushrax/OpenVR-SpaceCalibrator#24]
Since I am using multiple trackers, I have to use SteamVR null driver with multiple tracker receivers. In that case, I cannot connect my HMD and my tracker at the same time, the saved calibration profile is thus disabled. 

Is there a way to disable null driver and calibrate headset with my tracker first, and then enable null driver using the saved calibration profile?

Any suggestion would be much appreciated. Thanks! :)

**Comment by tina1998612** [comment]
Screenshot with null driver: 
![image](https://user-images.githubusercontent.com/19768276/91511328-03c2c280-e912-11ea-847e-0b3657b21bc0.png)

**Comment by pushrax** [comment]
The code currently makes some assumptions about an HMD being connected, but it would be easy to change.

Can you clarify your use case? Which specific devices will you have connected and tracking at the same time?
