### ISSUE TITLE
Calibration has stopped working with SteamVR Beta 1.14.9

### ISSUE THREAD

**Issue by sundansx** [pushrax/OpenVR-SpaceCalibrator#25]
I was on the SteamVR beta channel and all was working fine.  Yesterday Steam autoupdated to SteamVR 1.14.9.  My controllers appears at their default position when I fired up SteamVR.  Did calibration and they did not move.  Restarted comptuer and followed directions on this page and the controllers still did not move.  rolled steamvr back to the standard release and it started working.  I am using: 
- latest standard steam release, 
- latest nvidia drivers 452.06
- Odyssee+ WMR headset w/ WMR for SteamVR beta 1.2.353
- and v1.0 lighthouses.  
- Using SpaceCalibrator v. 1.0. 
- Windows 10 64bit, 1909
I am concerned that when this SteamVR beta rolls to a standard release that calibrator will break.

**Comment by dave11674** [comment]
yeah, got same here, as soon as the new beta is installed i get a runtime error from calibrator

- odyessy+

- lastest video drivers

- 2 x v1.0 lighthouse

- space cal v1.0

**Comment by NovaVoidHowl** [comment]
Its the same for me 

- Oculus Rift S
- latest Nvidia drivers (452.06)
- 4 x v2.0 lighthouse
- space cal v1.0

Of note is that OpenVR Advanced Settings could not fix the positioning either, no matter the offset applied the lighthouse tracked devices were always the same distance below me

**Comment by pushrax** [comment]
Thanks for the report. I’ll take a look this week.

**Comment by sundansx** [comment]
pushrax,
Here are some hints:
https://www.youtube.com/watch?v=UiZCXWbJ6nk 
FYI:
I just changed the 2 strings in your driver to reflect that post (006) and  compiled.  It started working again with the latest beta.
credit goes to  Dj Lukis.LTon in discord for finding the place in calibrator to make the change:
https://discord.com/channels/441662347141054474/450382693872697346

**Comment by pushrax** [comment]
This is now fixed. v1.1 will work on the current stable and beta versions of SteamVR. https://github.com/pushrax/OpenVR-SpaceCalibrator/releases/
