### ISSUE TITLE
SteamVr update issue

### ISSUE THREAD

**Issue by Euryyy259** [pushrax/OpenVR-SpaceCalibrator#26]
There is an issue with the openspace vr calibration program currently. You are unable to calibrate correctly with the new SteamVr update and it puts your calibration dots further away from you after you try to pair it successfully to your controller. Does not calibrate correctly and its only an issue with the program as people using vive only have no issues with calibration.

**Comment by emerekt** [comment]
from what i read its because steamvr updated IVRServerDriverHost from 005 to 006, input emulator is also broken because of that. i just hope valve add compatibility for it soon.

**Comment by pushrax** [comment]
Did you update to Space Calibrator v1.1 and still encounter an issue? This should have been fixed for some time now.
