### ISSUE TITLE
Trackers Won't Align To Body During/After Calibration

### ISSUE THREAD

**Issue by novetrix** [pushrax/OpenVR-SpaceCalibrator#27]
When I connect my trackers and enter the SteamVR menu, the trackers are in a triangle (two feet, hip) as I would expect, but quite far away from me.

Normally, when I use the hip tracker to calibrate, the others shoot off quite far away, and the hip tracker bounces around a bit, all three eventually resting where they should.

Recently, when I enter Calibration, the three trackers remain exactly in their original position before I pressed the button. When calibration reaches the second phase, the tracker symbols once again remain exactly where they are.

Finally, when calibration has completed, the symbols are exactly where they used to be.

I fixed this in the past by absolutely deleting EVERYTHING; Advanced Settings, Space Calibrator, and SteamVR itself. After all was said and done, after reinstalling it all, the calibration went back to working as it should, but today 9/18 it has gone right back to the three trackers simply hanging in their respective places, aligned properly to each other, but not to me, and I can do nothing about it.

**Comment by emerekt** [comment]
OVR advanced settings still works except  some things on it are kinda broken like space drag, you just need to not enable input emulator and hope valve fixes it soon,

**Comment by pushrax** [comment]
Did you update to Space Calibrator v1.1 and still encounter an issue? This should have been fixed for some time now.

**Comment by Euryyy259** [comment]
Yes i did update it and messed with some other stuff to fix my problem i appreciate the help.
