### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ChromiumIsotope** [pushrax/OpenVR-SpaceCalibrator#31]
Attempting to open the application gives a box with this message: "Space Calibrator driver unavailable, is SteamVR running and not in safe mode? Error: The system cannot find the file specified."
I really do not know what this means or what I did wrong. Yes, SteamVR is running and not in safe mode. I tried re-downloading Space Calibrator to see if it just installed incorrectly, and the same thing happened. The same thing will happen whether I try to open the application before I have any VR open or whether I am in VR and go to my desktop to open it.

**Comment by 200Tigersbloxed** [comment]
![image](https://user-images.githubusercontent.com/45884377/96185140-75c58a00-0f07-11eb-81d6-5658b108fcf1.png)

A message from the discord server regarding this issue

**Comment by BloggersUnited** [comment]
If you have any add-on blocked just go into settings in steam VR go to startup/shutdown then click manage add-on’s and unblock all add ons that steam VR has blocked then restart steam VR it worked for me.

**Comment by pushrax** [comment]
The error message has been improved.
