### ISSUE TITLE
Index Controllers Fly Out

### ISSUE THREAD

**Issue by xMako** [pushrax/OpenVR-SpaceCalibrator#33]
My index controllers work with my Rift S, but I have to use SteamVR Space Calibrator. When I launch Driver4Vr ( software to use kinect as vive trackers) to setup my kinect my index controllers fly and dissapear. Is this a compatability issue?

**Comment by pushrax** [comment]
It is possible there is a compatibility issue. I assume the Driver4Vr setup works with your Touch controllers?

**Comment by xMako** [comment]
yes i have. the same same issue is present. It is also present in KinectToVr. It looks like if I keep moving the controllers the drifting will lessen but if i keep them still they completely drift a nd disappear. I have to restart SteamVR to use them again.
![bvnjhk](https://user-images.githubusercontent.com/65842237/97099348-585a9380-165e-11eb-9c6d-422590999965.PNG)
![dsfdsgdfbdfh](https://user-images.githubusercontent.com/65842237/97099352-69a3a000-165e-11eb-8986-9d112b1c5cb5.PNG)

**Comment by xMako** [comment]
should I clear calibration then start steam vr with Driver4vr then try to calibrate it?

**Comment by xMako** [comment]
I tried to calibrate it with Driver4VR on and previous calibration clear. When I pressed calibrate it told me this.
![hgfgfdgdfg](https://user-images.githubusercontent.com/65842237/97099550-96f14d80-1660-11eb-94a3-d70eda3410ae.PNG)

**Comment by pushrax** [comment]
To fully understand what is happening here, I am going to need to figure out how exactly Driver4VR interacts with OpenVR. I asked in the Discord if anyone has run this setup before, maybe there will be something useful from that.

It's a bit hard to see behind the popup, but it looks like there are still only the two Knuckles devices. I would have expected Driver4VR to create a few tracker devices. Are they in a different target space?

**Comment by xMako** [comment]
![vhgj](https://user-images.githubusercontent.com/65842237/97118332-dd39c180-16df-11eb-91f3-5bbae033c5be.PNG)
they are in a different target space. I cant re-calibrate either because it says this. (In 1.2)
![vfbfdhg](https://user-images.githubusercontent.com/65842237/97118416-20943000-16e0-11eb-9b12-884000df613f.PNG)

**Comment by gb2111** [comment]
If drifting happens on both apps, I'd try if this is not related by any chance to IR emitters from Kinect, especially 2.0.
Install Kinect SDK and run Body Tracking demo. Don't start Driver4VR to ensure there is no interaction on SteamVR level.
If problem exist with just Body Tracking Example then try to place Kinect perpendicular to line between two base stations.

I hope I understand your problem correctly :)

Best,
Greg

**Comment by xMako** [comment]
@gb2111 It did happen again. When I turned on the tracking demo my Index controllers flew out. But when I turned it off they worked again. I tried setting them up perpendicular but the issue persisted. I believe it is related to infrared emitted. While searching online many had this issue with 1.0 base stations but some didn't because of their position. I'll keep trying different positions.

**Comment by xMako** [comment]
It was IR immitera
