### ISSUE TITLE
About how to integrate both Oculus Quest 2 and Valve knuckles in a PC. Is it possible?

### ISSUE THREAD

**Issue by castana1962** [pushrax/OpenVR-SpaceCalibrator#34]
Hi,
I am interested in using both Oculus Quest 2 and the Valve Knuckles to use its each finger tracking and let to the patients to improve your health injury, for that reason. Can I use this software to integrate both VR Devices?
Thanks for your time
Best Regards
Alejandro

**Comment by pushrax** [comment]
Hello Alejandro,

This configuration is possible, using Virtual Desktop, ALVR, or Oculus Link. However, the Quest has an unstable tracking frame of reference, and there are a variety of conditions that require recalibration. I would not recommend it at the moment, though you can certainly try it out and see for yourself if you have the hardware already.

https://github.com/pushrax/OpenVR-SpaceCalibrator/issues/30 will resolve that (likely to be implemented in December), by requiring a Vive tracker to be strapped to the HMD. It's not the most elegant solution, but it will work perfectly if you are able to set up that hardware.

**Comment by pushrax** [comment]
It seems many people run this today, as the tracking frame stability has improved. Though it’s definitely not perfect.
