### ISSUE TITLE
Left controller tracking loss when getting close to right controller.

### ISSUE THREAD

**Issue by Watercrown** [pushrax/OpenVR-SpaceCalibrator#38]
Hi,

So this works really well for the most part. When the controllers start getting close to each other however, the left controller starts to shift around and eventually even disappears sometimes. Any clue what the issue could be?

**Comment by pushrax** [comment]
That sounds like an issue with the controllers themselves (maybe hardware interference), and I can't think of any explanation that includes code in Space Calibrator.

What hardware are you using?

**Comment by Watercrown** [comment]
G2 HMD, Steam controller dongle, Vive tracker dongle, Index controllers and base stations.

The controllers worked fine with the Index HMD.

I think you are right about interference. It seems to get worse depending on which USB ports I use. I'm picking up another active USB extension and see if that makes the issue any better.
