### ISSUE TITLE
Register as overlay application to enable automatic launch

### ISSUE THREAD

**Issue by lukis101** [pushrax/OpenVR-SpaceCalibrator#4]
Need to provide a `manifest.vrmanifest` file together with executable and register as a vr application on runtime.
My guess would be [AddApplicationManifest](https://github.com/ValveSoftware/openvr/blob/64fc05966a109543a1e191a45e1ab3a25a651211/headers/openvr.h#L2080), example usage can be found over in [AdvancedSettings repository](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/5ee667a56b4a374c2a54d0e9b9c9d16d9e90e6fc/src/main.cpp#L74)

**Comment by pushrax** [comment]
The main subtasks (other than the manifest) are hooking up OpenVR input to ImGui and writing the rendered texture to the OpenVR framebuffer. It should be straightforward but will involve looking up more detailed examples/docs to get this working without a Qt event loop.

Also worth noting it should work fine to render both the overlay and the regular window, possibly just by fixing the window size to the OpenVR framebuffer size.

**Comment by lukis101** [comment]
Yeah, although with this, was mostly targeting just the application registering to OpenVR part instead of actual overlay rendering, as that requires more work.

**Comment by pushrax** [comment]
Implemented in https://github.com/pushrax/OpenVR-SpaceCalibrator/commit/5c36f6e9094729fca6e50ec4572072427ee0169c
