### ISSUE TITLE
My space callibrator just randomly stopped working a few days back

### ISSUE THREAD

**Issue by Zanegompf** [pushrax/OpenVR-SpaceCalibrator#44]
It says  "space Calibrator driver unavailable" when trying to set up full-body tracking on my Rift-S.
I've edited the SteamVR default file to allow multiple drivers and not require HMD yet it still doesn't work after months of working normally.
![DriverIssue](https://user-images.githubusercontent.com/32608439/103142359-b9323680-46b6-11eb-89e2-ba2d5fcb0737.jpg)

**Comment by Jphgamer14** [comment]
A friend of mine is also having this issue and i have no idea how to fix it.

**Comment by Obsidion-demise** [comment]
Was able to help a friend troubleshoot this issue, Steamvr settings>Startup/Shutdown>Manage Add-ons 
hit unblock all, then disable trackpad support(this seems broken as it always causes issues for me at least) then at the top there should be a restart steam VR button and you should be good

Hope this helps.

**Comment by pushrax** [comment]
I should update the message now that Safe Mode is not the way SteamVR presents this case to the user. Like @Obsidion-demise said, you need to go to Startup/Shutdown>Manage Add-ons in SteamVR settings, and unblock the Space Calibrator add-on. It could get blocked (along with other add-ons) if SteamVR crashes while Space Calibrator is loaded.

I'm keeping this issue open until I update the message.
