### ISSUE TITLE
HTC Vive touch controls not working.

### ISSUE THREAD

**Issue by SoulDesignerTom** [pushrax/OpenVR-SpaceCalibrator#49]
I've tested it in two games so far: The Wizards and Raw Data - on both games i can't walk - the touch pads on controlers does not work. It seems that every other buttons works well.

**Comment by pushrax** [comment]
This software shouldn't affect button/touchpad inputs in any way. The way the driver hooks are implemented should make that impossible. Is this still occurring and do you have any more details?

**Comment by SoulDesignerTom** [comment]
I've found out that there was a different issue.
Controllers where not configured well - i mean bindings of actions was not assign properly.
To be honest i've spend a lot of time trying to configure them.

I'm not sure if this is your software issue - cause when i was playing games with HTC Vive - everything works without issues.
But when i was using your software + Vive controllers + HP Reverb G2 - bindings wasn't working well and for a lot's of titles requiers indivudual configurations.

**Comment by pushrax** [comment]
The issue is probably a fundamental result of using an unexpected HMD with different controllers. SteamVR or the game may have tried to apply the input binding for the wrong type of controller. Space Calibrator doesn't do anything related to inputs, just position adjustments. Perhaps a guide on how to configure bindings would be useful to people. I haven't had an issue with this in the past but maybe something changed.

**Comment by SoulDesignerTom** [comment]
Maybe you are right - i was also using OpenVR Advanced Settings: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/releases

Cause this is required to use those controllers with Reverb G2.

> fundamental result of using an unexpected HMD with different controllers

but isn't this software exactly for it?

**Comment by pushrax** [comment]
This software specifically aims to handle positional calibration. IMO SteamVR should correctly handle input mapping and not leave it up to 3rd party apps. SteamVR has also changed the underlying APIs for input mapping multiple times and supporting specific workarounds across those changes would be a lot of work.

**Comment by SoulDesignerTom** [comment]
That's true, but i don't have any issues with calibration of my controllers when i use dedicated headset.
The offset just began to apear when i was trying to mix Reverb with Vive controllers.
