### ISSUE TITLE
Disable calibration when one of VR systems used alone

### ISSUE THREAD

**Issue by deinlandel** [pushrax/OpenVR-SpaceCalibrator#5]
Hello,
I tried your program with WMR Headset and Vive controllers. Calibration worked, but when I switched back to Vive, controllers were still with calibration offsets floating way off. I managed to enter to overlay and reset "source" system, after this controllers "returned" to their proper places.

It would be nice to apply offsets only when headset to which calibration was performed is active.

And another problem: it seems space calibrator openvr driver messes with room setup and chaperone bounds. When using only Vive, playspace is floating at the wrong position. Also, chaperone not working. I tried running room setup multiple times, but it didn't help. Only uninstalling SpaceCalibrator and running Room Setup again fixed things.

So in current state it's impossible to "switch" headsets and use them separately when SpaceCalibrator is installed. I really hope this could be fixed.

**Comment by pushrax** [comment]
I'll get this fixed this weekend!

**Comment by pushrax** [comment]
I'll get this fixed this weekend! To work around it until then, try disabling the "Paste Chaperone Bounds automatically" checkbox.

**Comment by pushrax** [comment]
Done in v0.9 - better late than never!
