### ISSUE TITLE
Oculus Rift + 3 Trackers and 2 BS (2.0)

### ISSUE THREAD

**Issue by Happy347** [pushrax/OpenVR-SpaceCalibrator#51]
I haven't found anything about my exact problem, so will try asking here.

I have correctly placed Base Stations 2 on the wall, seeing each other and play area. 
Calibration works perfectly (position is accurate), but my problem is connected with use of 2 Base Stations.

My feeling is, that Tracker does not register that there are actually 2 Base Stations, not just one - so when I face BS "A" it is ok, but when "A" is not visible and only BS "B" sees the tracker, the Calibration is broken (inverted, like it assumes that "B" is actually an "A" Base Station). The 2 BSs somehow does not work together in my case.

I have tried to unplug one BS, and above described problem was gone. 
And also other Tracker problems, which I will describe below.

It was quite ofthen that some of the trackers stopped moving, stayed at place or reseted and stayed at the center of the play area rendered invisible (only battery status). This also happened with only 2 BS active, with one, no problems like that.

Can you please confirm that Calibrator should work with 2 Base Stations 2.0?

Today I will to unplug the other Base Station, to try-out if there is or is not an issue in Base Station itself.
I have also read (most probably for BS 1.0) something about setting BS as an B and C, but BS 2.0 have no buttons in the back for doing that. The information on the internet around Base Stations and Trackers feels incomplete at least. I also stupidly bought Bluetooth to later notice that there is some special kind of Bluetooth only in HTC and Index Headsets to coomunicate with BSs - and I am now thinking if that might be causing my issues, that I miss this Bluetooth device, so Base Stations works in some kind of stand-alone mode instead of cooperating.

**Comment by Raivr-dev** [comment]
I'm not the SpaceCalibrator dev, but: 
SpaceCalibrator wouldn't know how many base stations you have. It just gets position data from OpenVR.
You could try to set your base stations to another channel using a paperclip. Take a look here:

https://www.reddit.com/r/vive_vr/comments/c8bil1/is_there_a_way_to_change_base_station_20_channels/

**Comment by Happy347** [comment]
I missed this information, sounds like it will solve my problem. Will confirm that after work.
Thank you!

**Comment by jgr526** [comment]
The synced universe is always created based on a "Master" base station.
When you turn on your steam controllers to start a new steam vr session,
the first visible base station in the session has a lot of importance in
how the steam universe is aligned. Always start up steam with the "correct"
Master base station visible to your steam controllers and attempt to hide
the slave base stations from the controllers when turning them on. That
usually works for avoiding misalignment issues in the steam universe.

**Comment by Happy347** [comment]
Thanks for inputs. Setting-up the channel was the root cause of all my problems. Now the tracking is great.
