### ISSUE TITLE
HP Reverb G2 with Oculus CV1 Sensors and Touch Controllers

### ISSUE THREAD

**Issue by matzetube** [pushrax/OpenVR-SpaceCalibrator#52]
I've tried it before, but Steam VR doesn't recognize the sensors when I start it with the Reverb. Could that be made possible somehow?

**Comment by pushrax** [comment]
This isn't possible at the moment. The Oculus driver only works when the HMD is enabled.

I started working on proxy driver to do this one weekend last year. It's like 80% working - the controllers render properly, the inputs work, and the controllers move around, but I stopped before I got the calibration to the target space working.

It's probably not too much effort to finish it but I currently have other priorities.

**Comment by Hotohori** [comment]
That would be really nice if that could working. Have still laying my Rift CV1 with 3 sensors laying around and wish since a long time i still could use the controllers. After Lighthouse that setup was the best tracking and the controllers are also good and well balanced.

**Comment by not-important-vr** [comment]
This was accomplished recently, see relevant thread here:  https://www.reddit.com/r/MixedVR/comments/l42zp4/announcing_oculus_touch_as_mixevr_controller/

**Comment by matzetube** [comment]
Very nice ^^ It works pretty well ^^ if that is still polished it could be really good
