### ISSUE TITLE
No menu in SteamVR

### ISSUE THREAD

**Issue by Mintycraft** [pushrax/OpenVR-SpaceCalibrator#55]
While the space cal window shows up just fine on the desktop, there is only a blank space when I try to pull up the same menu from within SteamVR. The OVR Advanced Settings menu comes up fine, so it is only this menu that does not.
![2021-03-11 00_29_48-Window](https://user-images.githubusercontent.com/52329037/110758639-95848400-8201-11eb-9116-7b14b7073634.png)

**Comment by MrGranto** [comment]
I am having the same issue, it makes it so I cannot properly recalibrate my index controllers with my HP Reverb G2. Everything else works fine. I have tried uninstalling and reinstalling several times to no avail.

**Comment by Bakurawr** [comment]
Just to add a note here.

I had the same issue while I had my AMD Vega 64 (driver ver 20.12.1). Switched out to a Nvidia RTX 3090 and now it suddenly just works fine so my guess is that it might be an AMD rendering issue.

_My previous workaround was just accessing the Space Cal window through the desktop mode button if it might help anyone with the same issue._

**Comment by MrGranto** [comment]
Update: I noticed the space calibrator will open on the desktop now instead of the SteamVR Hub. While in SteamVR if I select desktop I am still able to use the space calibrator. Try loading up SteamVR and see if this is the same case for you.

**Comment by nullstalgia** [comment]
Also running AMD GPU (RX 5700 XT). I have the exact same issue with Natural Locomotion and this app.

**Comment by pushrax** [comment]
This does look like the same issue, thank you @nullstalgia. I will paste the relevant section of their documentation here, which contains a workaround that may be useful to people in this thread:


> - **Issue:** Upon clicking ADV-Settings icon no page shows up.
>   - **Cause:** related to multiple GPU systems Displaying OpenGL on low power GPU first (IGPU's primarily) [some programs such as alvr may also cause this issue] 
>   - **Solution for Nvidia GPU's:** go to Nvidia Control Panel -> manage 3D settings -> Program Settings -> add Advanced Settings, and change `OpenGL Rendering GPU` to the GPU your VR is connected to.
>   - **Solution for Windows (1803+):** go to Settings -> System -> Display -> Select `Classic App` and Browse for `AdvancedSettings.exe` -> Click Options -> Select High Performance

At some point I'll try adding this code to export symbols that automatically enable high performance:
```c++
extern "C" __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
extern "C" __declspec(dllexport) DWORD AmdPowerXpressRequestHighPerformance = 0x00000001;
```

**Comment by Mintycraft** [comment]
> This does look like the same issue, thank you @nullstalgia. I will paste the relevant section of their documentation here, which contains a workaround that may be useful to people in this thread:
> 
> > * **Issue:** Upon clicking ADV-Settings icon no page shows up.
> >   
> >   * **Cause:** related to multiple GPU systems Displaying OpenGL on low power GPU first (IGPU's primarily) [some programs such as alvr may also cause this issue]
> >   * **Solution for Nvidia GPU's:** go to Nvidia Control Panel -> manage 3D settings -> Program Settings -> add Advanced Settings, and change `OpenGL Rendering GPU` to the GPU your VR is connected to.
> >   * **Solution for Windows (1803+):** go to Settings -> System -> Display -> Select `Classic App` and Browse for `AdvancedSettings.exe` -> Click Options -> Select High Performance
> 
> At some point I'll try adding this code to export symbols that automatically enable high performance:
> 
> ```c++
> extern "C" __declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
> extern "C" __declspec(dllexport) DWORD AmdPowerXpressRequestHighPerformance = 0x00000001;
> ```

**Comment by nullstalgia** [comment]
Nice to see you have a fix! I wouldn't close the issue until @pushrax is able to get a fix in for everyone first. It helps keep us developers know what issues are still out there. :)

**Comment by pushrax** [comment]
This does still seem to happen for AMD cards.

**Comment by uelef** [comment]
I also got the problem on my AMD Radeon Pro 5700 XT (an iMac with Win 10 on Bootcamp) … I open space cal within SteamVR and the window is empty. It looks similar to the screenshot in the beginning. I was hoping to use my Index controllers with an HP Reverb 2, but it does not work.
Any fix ahead?

**Comment by xavion-lux** [comment]
It does work for me. I'm on Vega 64.

**Comment by xavion-lux** [comment]
I'm speaking about OVRAS, sorry for not mentioning it.

**Comment by uelef** [comment]
Open VR Advanced Settings works without any problems on my computer. It's only Space Cal that makes problems.
Using the desktop window does not work either. I can see the window but mouse clicks on selecting the controllers or using buttons do not work. Nothing happens.

**Comment by pushrax** [comment]
>  I can see the window but mouse clicks on selecting the controllers or using buttons do not work.

Can you confirm that you had the SteamVR dashboard/overlay closed? If the overlay is open then the desktop window does not accept input.

**Comment by uelef** [comment]
Ok, closing the VR overlay helped to react inside the Space Cal window. In Germany it's to late to test calibrating now – I will do it tomorrow. Thanks for your support.

**Comment by uelef** [comment]
Ok, using the desktop window calibration now worked. The Steam overlay still does not show anything – and I would appreciate if it would work … Thanks for your help again!

**Comment by pushrax** [comment]
I now have an AMD card and reproduced this issue today. For some reason the code in OpenVR to copy the overlay image to a DirectX compatible texture didn't like using a texture with GL_RGBA internalFormat. GL_RGBA8 fixed it.

Released version 1.4 includes the fix. https://github.com/pushrax/OpenVR-SpaceCalibrator/releases

**Comment by FoxBun** [comment]
hi i have a same problem but this one is different on its not the same one I am having a problem were it no working its saying that it is unavailable and I tried everything pls help me

**Comment by FoxBun** [comment]
hi i have a same problem but this one is different on its not the same one I am having a problem were it no working its saying that it is unavailable and I tried everything pls help me
