### ISSUE TITLE
Runtime Error: Failed to Create Window

### ISSUE THREAD

**Issue by GilbertRPG** [pushrax/OpenVR-SpaceCalibrator#58]
### OpenVR is unable to create a runtime window when I am utilizing just my iGPU on the affected laptop. 

Is there a way to define what GPU to select when generating a window? **Attached is DxDiag report.** _Am currently in the process of updating all drivers and BIOS systems to see if it's something related on my end._
[DxDiag.txt](https://github.com/pushrax/OpenVR-SpaceCalibrator/files/6268231/DxDiag.txt)

**Comment by pushrax** [comment]
This is probably fixed in the latest release, feel free to reopen if not.
