### ISSUE TITLE
Problem caused by the OpenVR Space Calibrator tool that makes SteamVR stop reporting your play area size properly

### ISSUE THREAD

**Issue by vukeifl** [pushrax/OpenVR-SpaceCalibrator#62]
I ran into a problem in the game "The thrill of the fight". Its essence is as follows: 
I started playing this game on the Reverb G2 and everything was great. But yesterday I switched to index controllers (on G2) and now in "The thrill of the fight" my opponent appears right in me (not in front of me) at the beginning of each round. I tried switching back to my old WMR controllers, but the problem persisted.
I contacted the developer of the game on Steam and he told me that "this is a problem caused by the OpenVR Space Calibrator tool that makes SteamVR stop reporting your play area size properly".
Can I handle this problem myself? Many thanks!

**Comment by Raivr-dev** [comment]
Did you have the option checked in SpaceCalibrator where it saves and restores the chaperone boundaries? Maybe something went wrong there. 
Do you run other overlay apps that affect the chaperone, such as OVRAS (OVR Advanced Settings)? Disable those and try again.

**Comment by LOSTIE09** [comment]
so ive been lagging and when i lag i uninstall the software and play with no lag i cant use fbt anymore bc of it please help.
