### ISSUE TITLE
hmd file????

### ISSUE THREAD

**Issue by deusumbra1** [pushrax/OpenVR-SpaceCalibrator#66]
whenever i try to launch it it says hmd file not found

**Comment by pushrax** [comment]
What exactly is saying this? Is it in a popup from SteamVR? I’m not aware of any “hmd file” and what it might be used for. A screenshot would be helpful for troubleshooting your problem.

**Comment by deusumbra1** [comment]
I got it to fix i just had to set my hmd to false so i could open steam vr
without a headset on
