### ISSUE TITLE
Where to edit/adjust the relative scale experimental feature?

### ISSUE THREAD

**Issue by Valve-Anti-Cheat** [pushrax/OpenVR-SpaceCalibrator#67]
Title - can't seem to find it. Also, still doesn't show in steam overlay even after 1.3 update.

**Comment by pushrax** [comment]
Press the "Edit Calibration" button after you have a valid calibration. See Brian's guide for how to use it https://old.reddit.com/r/MixedVR/comments/qpj22e/new_official_space_calibrator_release_possible/

The update fixed the overlay for NVIDIA users with an integrated GPU, but not for AMD users with specific GPUs who are experiencing a missing overlay.

**Comment by Valve-Anti-Cheat** [comment]
Thanks for the quick response <3
