### ISSUE TITLE
Space Cal not showing up in steamvr embed

### ISSUE THREAD

**Issue by LivVR** [pushrax/OpenVR-SpaceCalibrator#69]
Hello!

The issue that I currently have has never worked but I wanna try and fix all my bugs that I currently have. When I startup steamvr I always have to use space calibrator via the desktop and press start calibration from there, and it never appears in my steamvr overlay. The space cal button is there but when I press it its just a transparent window and nothing appears. 

I use oculus quest 2 with 2.0 basestations and 3.0 trackers. I've tried running steamvr without space cal as a startup app, i've tried reinstalling space calibrator, I've tried reinstalling and turned on the beta version of steamvr.

I really appreciate it if someone could help me fix this issue, thanks.

**Comment by pushrax** [comment]
If you have certain AMD cards, you're likely running into #55, which doesn't have any fix yet.

**Comment by pushrax** [comment]
Fixed in v1.4
