### ISSUE TITLE
Calibration not picked up at startup

### ISSUE THREAD

**Issue by muchcharles** [pushrax/OpenVR-SpaceCalibrator#7]
When starting things up my calibrations never seem to be picked up from previous runs.   Is copy chaperone bounds to profile required for that functionality? When calibrating, I do see it say the calibration was saved to config.

Also, when I am using a WMR and calibrate Vive controllers, as soon as I turn them off (or they turn off due to idle) and back on again they are uncalibrated again, even though steamvr and the calibrator program never exited.

**Comment by pushrax** [comment]
There seem to be a couple cases that prevent profiles from being saved properly:

1. Steam installed to a different drive than SteamVR
2. SteamVR sometimes doesn't create the config folder

I plan to use a different approach to saving the configuration, until then it can be worked around by either putting SteamVR in the same drive as Steam if 1. is your issue, or creating the folder `config/01spacecalibrator` in the Steam folder if 2. is your issue.

**Comment by muchcharles** [comment]
Hey, I think I found the issue:

```cpp

void LoadProfile(CalibrationContext &ctx)
{
    ctx.validProfile = false;

    std::ifstream file(ConfigFileName());
    if (!file.good())
    {
        std::cout << "Profile missing, trying fallback path" << std::endl;
        // Fallback to working directory, which was the default for a long time.
        file = std::ifstream("openvr_space_calibration.json");
    }

```

It tries to create the file, but it doesn't try to create the directory (`\\..\\..\\..\\config\\01spacecalibrator\\calibration.json`).

When I manually created the directory here it worked: `C:\\Program Files (x86)\\Steam\\config\\01spacecalibrator`

**Comment by pushrax** [comment]
As of v1.0 the config is stored in the registry.
