### ISSUE TITLE
Constant HMD Tracker Calibration Updates?

### ISSUE THREAD

**Issue by Activusto** [pushrax/OpenVR-SpaceCalibrator#70]
Hi there, it's been about a year since the idea of using a Vive Puck/Tundra Tracker on the HMD for Constant Calibration got suggested.
https://github.com/pushrax/OpenVR-SpaceCalibrator/issues/30

Just wondering if there's been any updates as it was planned for a November/December release in 2020.
This is a feature well requested by a ton of people and I think it's only fair to give out an update considering it's been a year since the planned implementation.

Is this still planned?

**Comment by pushrax** [comment]
See https://github.com/pushrax/OpenVR-SpaceCalibrator/issues/30
