### ISSUE TITLE
Space Cal Runtime Error

### ISSUE THREAD

**Issue by RoseFluffle** [pushrax/OpenVR-SpaceCalibrator#77]
Upon trying to run Open Space Calibrator I get a pop up window that reads "Runtime Error" -- "Failed to Create Window". Now I've tried pretty much every option in regards to fixing this and I'm just not sure what to do, so I came here in hopes to find some sort of solution.

**Comment by wild0** [comment]
Sorry, but I have the same issue, how u fix it?

**Comment by RadarBirb** [comment]
any fix yet?
