### ISSUE TITLE
Oculus and Vive

### ISSUE THREAD

**Issue by ChurchN** [pushrax/OpenVR-SpaceCalibrator#8]
Hello I love the program it makes the set up and paring easy. But I have been having an issue that has been make a bit of trouble for me, for some reason when ever I have the body tracker with my Oculus. Steam for some reason forgets room set up and the places me in the floor i downloaded another mod for advanced steam settings which should have the floor fixed but it has no effect could I have downloaded something wrong possibly?

**Comment by pushrax** [comment]
As of v0.8, this is fixed by the chaperone management feature. The README file contains instructions for how to use this.
