### ISSUE TITLE
Knuckles DV buttons not working when used with rift

### ISSUE THREAD

**Issue by FupsGamer** [pushrax/OpenVR-SpaceCalibrator#9]
I have my knuckles setup with my rift, its tracks fine but I cant seem to press any button and the hands are still the touch, I can also not see the left/ right sign on the controller.

**Comment by FupsGamer** [comment]
Everything seems to work normally except the main hands are the touch, is there a way to change that, btw works great with wands

**Comment by pushrax** [comment]
Is this specific to one application or even in SteamVR home / dashboard?
