### ISSUE TITLE
OpenVR SpaceCalibrator won't track quest 2 controller

### ISSUE THREAD

**Issue by babyemojesus** [pushrax/OpenVR-SpaceCalibrator#93]
I can use SteamVR on my Quest 2 absolutely fine, and my headset and controllers work to press everything I need to and track well. However, when I try to use the calibrator with my controller and a tracker, there is an issue saying that my controller is not tracked.
![OpenVR issue](https://user-images.githubusercontent.com/104721951/197370053-0dd3444d-7e54-41a4-92cf-7220faf9caa4.png)

I would like to be able to use full body on my quest 2 and have been unable to find anything online to help

**Comment by LilKhloe** [comment]
Read what it is saying, the "Target device is not tracking". Your tracker is probably improperly linked to it's dongle.

**Comment by babyemojesus** [comment]
How so? It works fine tracking in every game it's just when it's trying to calibrate specifically in OpenVR. How do I make sure it's tracking properly when there seems to be no issue with the tracking?:(

**Comment by LilKhloe** [comment]
You don't understand how the program works. Your Vive/Tundra tracker is the thing not being tracked correctly. Also, it's impossible that the trackers "work fine in every other game" if you can't even properly calibrate the two play spaces together.

**Comment by babyemojesus** [comment]
I do not understood how the program works that's why I'm asking here. I see what you mean now about the target device being the tracker, I misread what it said so I'm sorry about that. I was trying to say my controller works fine in any other game but I can see now that's not the issue
So, if it is the vive tracker not tracking correctly- it seems to be soley with calibrating the play spaces together as when I've used a different headset with those trackers I had no issue connecting those play spaces. Do you how can i fix this issue? I can see it move in steamvr as if it is being tracked and the light is green and it has the same issue for all three trackers.
I'm sorry I don't know how the program works, I just don't know where else to ask for help and the only issue seems to be within the OpenVR calibration process

**Comment by LilKhloe** [comment]
What other headset are you using with those trackers? Also, make sure that "activateMultipleDrivers" is set to true in your steamvr.vrsettings file (OVR Space Calibrator should auto do this but check regardless)
If that doesn't work then I'd recommend re-pairing the Vive trackers to their dongles through SteamVR.

**Comment by babyemojesus** [comment]
I have a Quest 2, never had an issue with my rift previously
I will try the activateMultipleDrivers thing and re-paring thank you

**Comment by BeardedGorlok** [comment]
Did the repairing worked? Ive been having the same issues for a while and ive tried damn near everything but change my router and repairing the trackers to their dongles.

**Comment by babyemojesus** [comment]
> Did the repairing worked? Ive been having the same issues for a while and ive tried damn near everything but change my router and repairing the trackers to their dongles.

Unfortunately no, neither re-pairing or checking the activateMultipleDrivers settings worked
I did a clean reinstall of the Oculus client, SteamVR, and OpenVR and that seem to fix the issue
